Add sync to iOS tutorial
Latch/openkit pull request #12
Opened 2023-05-09 18:12 UTC by duff-latch

2023-05-09 18:17 UTC, nakulny requested changes

2023-05-09 18:17 UTC, nakulny commented on documentation/ios_tutorial.md
> +
@duff-latch @Ian-latch We should add something here about what a sync actually is? And what situations one might want to do one?

2023-05-09 18:19 UTC, Ian-latch commented
Sync allows your mobile client to act as a bridge to Latch backend for
uplink and downlink data requests including battery, timestamp, activity
logs, and engineering logs.

Ian Dyer (He/Him)

Senior Product Manager

***@***.***



<https://www.latch.com>


On Tue, May 9, 2023 at 11:18 AM Nakul Garg ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In documentation/ios_tutorial.md
> <https://github.com/Latch/openkit/pull/12#discussion_r1188974913>:
>
> > @@ -80,6 +80,23 @@ latch.startProximityUnlock()
>  latch.stopProximityUnlock()
>  ```
>
> +## Sync
> +
>
> @duff-latch <https://github.com/duff-latch> @Ian-latch
> <https://github.com/Ian-latch> We should add something here about what a
> sync actually is? And what situations one might want to do one?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Latch/openkit/pull/12#pullrequestreview-1419215759>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A32JBQACO7IWU5G6PXUX7L3XFKC5VANCNFSM6AAAAAAX3U6NHY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-09 18:25 UTC, Ian-latch commented
That's great. I'm aligned with that.

Ian Dyer (He/Him)

Senior Product Manager

***@***.***



<https://www.latch.com>


On Tue, May 9, 2023 at 11:24 AM Nakul Garg ***@***.***> wrote:

> Sync allows your mobile client to act as a bridge to Latch backend for
> uplink and downlink data requests including battery, timestamp, activity
> logs, and engineering logs. Ian Dyer (He/Him) Senior Product Manager *@*.***
> https://www.latch.com
> … <#m_3345077331399394255_>
> On Tue, May 9, 2023 at 11:18 AM Nakul Garg *@*.*> wrote: @.** requested
> changes on this pull request. ------------------------------ In
> documentation/ios_tutorial.md <#12 (comment)
> <https://github.com/Latch/openkit/pull/12#discussion_r1188974913>>: > @@
> -80,6 +80,23 @@ latch.startProximityUnlock() latch.stopProximityUnlock()
> ``` +## Sync + @duff-latch <https://github.com/duff-latch>
> https://github.com/duff-latch @Ian-latch <https://github.com/Ian-latch>
> https://github.com/Ian-latch We should add something here about what a
> sync actually is? And what situations one might want to do one? — Reply to
> this email directly, view it on GitHub <#12 (review)
> <https://github.com/Latch/openkit/pull/12#pullrequestreview-1419215759>>,
> or unsubscribe
> https://github.com/notifications/unsubscribe-auth/A32JBQACO7IWU5G6PXUX7L3XFKC5VANCNFSM6AAAAAAX3U6NHY
> . You are receiving this because you were mentioned.Message ID: *@*.***>
>
> I also might recommend adding on:
>
> "In times of troubleshooting, a sync is recommended to either resolve the
> issue or provide Latch with full information around the issue."
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Latch/openkit/pull/12#issuecomment-1540665827>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A32JBQCBUPV46GNTCGKIFRTXFKDU3ANCNFSM6AAAAAAX3U6NHY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-09 18:47 UTC, EDLuke approved these changes

2023-05-11 15:54 UTC, nakulny approved these changes

2023-05-11 15:57 UTC, merged